version: '3.8'

services:
  db:
    container_name: todo.bd.postgres
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - todo:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yoke2.famous
      - POSTGRES_DB=todo

  migrations:
    links:
      - db
    depends_on:
      - db
    build:
      context: ./backend
    command:
      [
        './wait-for-it/wait-for-it.sh',
        'todo.bd.postgres:5432',
        '--',
        'npm',
        'run',
        'migrate',
      ]
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=todo
      - POSTGRES_HOST=todo.bd.postgres
      - POSTGRES_PASSWORD=yoke2.famous

  api:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=todo
      - POSTGRES_HOST=todo.bd.postgres
      - POSTGRES_PASSWORD=yoke2.famous

volumes:
  todo:
