version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - todo:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yoke2.famous
      - POSTGRES_DB=todo

  api:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=todo
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=yoke2.famous
      - JWT_SECRET=todo-api-91afbfa0-a385-4242-9239-721b12361cc2
      - JWT_REFRESH_SECRET=todo-api-8de9d8e4-5ff9-4638-95bb-312081ccd7e5

volumes:
  todo:
