FROM node:20-alpine

RUN apk add --no-cache netcat-openbsd

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Copy the entrypoint script
COPY entrypoint.sh /app/

EXPOSE 3000

# Set the entrypoint script to be executed
ENTRYPOINT ["./entrypoint.sh"]