FROM node:20-alpine

RUN apk update && apk add git

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN git clone https://github.com/vishnubob/wait-for-it.git

EXPOSE 3000

CMD npm run start